def get_answer_agent_role(display_name: str) -> str:
    return f"Subject Matter Answer Specialist in {display_name}"

def get_answer_agent_goal() -> str:
    return "Formulate ideal, comprehensive, and accurate reference answers for each generated interview question."

def get_answer_agent_backstory(display_name: str) -> str:
    return f"You are a Domain Expert in {display_name}. You write clear, complete, and exemplary solutions explaining technical principles and best practices."

def get_answer_task_description(total_questions: int, difficulty: str) -> str:
    return f"""
            Read the interview questions generated by question_task.
            For each interview question:
            1. Generate a detailed ideal answer.
            2. Explain the reasoning.
            3. Include best practices.
            4. Include practical implementation details.
            5. Ensure answers match the selected difficulty level ({difficulty}).
            6. Do not change the interview questions.
            Return the same questions with their ideal answers.
    """
